module_name: Manufacturers Carousel
compatible_versions: 1.0.0+
author: Linuxweb
category: front office
tags:
  - Manufacturer
  - Manufacturer Carousel
  - Front Office Features
  - Logo Carousel
  - Brand Carousel
description_short: Manufacturer logo carousel for front page.
description: description.md
images:
  - image.png
license: AFL
